import React, { useEffect, useMemo, useState } from 'react'
import { Archive, ArchiveRestore, BedDouble, BriefcaseBusiness, CalendarDays, Check, ChevronLeft, ChevronRight, CirclePlus, ClipboardCheck, Clock3, Copy, Dumbbell, Eye, EyeOff, GripVertical, Home, Lightbulb, MoonStar, Palette, PawPrint, Pencil, Pin, PinOff, Repeat2, Sparkles, StickyNote, Trash2, Utensils, WashingMachine, X } from 'lucide-react'
import { loadState, saveState } from './storage'

const COLORS=[['blue','Trabalho','#3f6ff2'],['green','Saúde','#2f9b62'],['purple','Estudo','#7a55d9'],['yellow','Casa','#d29a18'],['orange','Pessoal','#dd6f2b'],['red','Importante','#d94f4f'],['gray','Neutro','#68706a'],['pink','Lazer','#c34f86']].map(([key,label,hex])=>({key,label,hex}))
const ICONS={work:BriefcaseBusiness,gym:Dumbbell,dogs:PawPrint,study:ClipboardCheck,trash:Trash2,food:Utensils,laundry:WashingMachine,sleep:BedDouble,note:StickyNote,idea:Lightbulb,default:Clock3}
const WEEK=[{key:1,short:'Seg'},{key:2,short:'Ter'},{key:3,short:'Qua'},{key:4,short:'Qui'},{key:5,short:'Sex'},{key:6,short:'Sáb'},{key:0,short:'Dom'}]
const ptDate=new Intl.DateTimeFormat('pt-BR',{weekday:'long',day:'2-digit',month:'long'})
const ptMonth=new Intl.DateTimeFormat('pt-BR',{month:'long',year:'numeric'})
const id=()=>crypto.randomUUID()
const keyOf=d=>[d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')
const monthKey=d=>keyOf(d).slice(0,7)
const addDays=(date,n)=>{const d=new Date(date);d.setDate(d.getDate()+n);return d}
const colorHex=k=>COLORS.find(c=>c.key===k)?.hex||'#68706a'
const cap=s=>s.charAt(0).toUpperCase()+s.slice(1)
const toMin=t=>{if(!t)return 0;const[h,m]=t.split(':').map(Number);return h*60+m}
const fromMin=n=>String(Math.floor((n%1440)/60)).padStart(2,'0')+':'+String(n%60).padStart(2,'0')

function classify(title=''){
 const s=title.toLowerCase()
 const rules=[
  [['academia','treino','caminhada','cachorro','cachorros','passear'],['green','gym']],
  [['estudar','estudo','curso','aula','ler','leitura'],['purple','study']],
  [['trabalho','escritório','reunião','office','expediente'],['blue','work']],
  [['lixo','limpar','limpeza','banheiro','casa','pano'],['yellow','trash']],
  [['roupa','lavar roupa','lavanderia'],['yellow','laundry']],
  [['comida','cozinhar','marmita','mercado','almoço','jantar'],['orange','food']],
  [['dormir','sono','acordar'],['gray','sleep']],
  [['prioridade','urgente','importante'],['red','default']],
  [['lazer','filme','jogo','descanso','livre'],['pink','default']]
 ]
 for(const [terms,result] of rules)if(terms.some(t=>s.includes(t)))return {color:result[0],icon:result[1]}
 return {color:'gray',icon:'default'}
}
function seed(){
 const routine=(title,time,endTime,days,color,icon,details='')=>({id:id(),title,time,endTime,days,color,icon,details})
 return {version:3,routines:[
  routine('Sono','23:00','08:00',[1,2,3,4,5,6,0],'gray','sleep','Horário-base para dormir e acordar.'),
  routine('Colocar lixo para fora','08:10','',[1,3,5],'yellow','trash'),
  routine('Trabalho — entrada','09:00','',[1,2,3,4,5],'blue','work'),
  routine('Almoço','12:00','13:00',[1,2,3,4,5],'orange','food'),
  routine('Academia','12:05','13:00',[1,2,5],'green','gym','Academia perto de casa; ajustar nos dias de escritório.'),
  routine('Trabalho — saída','18:00','',[1,2,3,4,5],'blue','work','Encerrar e anotar o próximo passo antes de fechar.'),
  routine('Passear com os cachorros','18:30','19:00',[1,2,3,4,5,6,0],'green','dogs'),
  routine('Estudar 1h','20:00','21:00',[1,2,3,4,5,6,0],'purple','study'),
  routine('Projeto pessoal','21:10','22:00',[2,6],'orange','work'),
  routine('Planejar amanhã','22:15','22:25',[1,2,3,4,5,6,0],'purple','study'),
  routine('Lavar roupa','19:00','',[2,4,6],'yellow','laundry'),
  routine('Passar pano / limpeza rápida','19:10','',[2],'yellow','trash'),
  routine('Limpar banheiro','19:10','',[4],'yellow','trash'),
  routine('Reciclável','09:00','',[6],'yellow','trash'),
  routine('Limpeza maior da casa','10:00','12:00',[6],'yellow','trash'),
  routine('Preparar marmitas / congelados','15:00','17:00',[0],'orange','food'),
  routine('Planejar a semana','20:00','20:30',[0],'purple','study'),
  routine('Noite livre','20:00','23:00',[5],'pink','default')
 ],tasks:[
  {id:id(),title:'Dia de escritório',date:'2026-09-09',time:'08:00',endTime:'18:30',color:'blue',icon:'work',details:'Deslocamento + trabalho presencial.'},
  {id:id(),title:'Home office',date:'2026-09-10',time:'09:00',endTime:'18:00',color:'green',icon:'work',details:'Exceção desta semana.'},
  {id:id(),title:'Repor marmitas no freezer',date:'2026-09-13',time:'17:00',endTime:'',color:'orange',icon:'food',details:'Criar estoque anti-delivery.'},
  {id:id(),title:'Revisar o que funcionou na rotina',date:'2026-09-20',time:'19:30',endTime:'20:00',color:'purple',icon:'study',details:'Manter o que funcionou e simplificar o resto.'},
  {id:id(),title:'Planejar outubro',date:'2026-09-27',time:'19:30',endTime:'20:15',color:'red',icon:'default',details:'Revisar compromissos, tarefas da casa, estudo e lazer.'}
 ],priorities:{},completions:{},notes:[
  {id:id(),title:'Ideias para projetos pessoais',body:'• Melhorias do Minha Rotina\n• Ideias rápidas que surgirem durante a semana',category:'Ideias',color:'orange',favorite:true,archived:false,private:false,createdAt:Date.now()},
  {id:id(),title:'Checklist da casa',body:'Lixo seg/qua/sex\nReciclável sábado\nRoupa 2–3x por semana\nBanheiro e pano durante a semana',category:'Casa',color:'yellow',favorite:false,archived:false,private:false,createdAt:Date.now()}
 ],noteCategories:['Ideias','Casa','Trabalho','Estudo','Pessoal'],quickTemplates:[
  {id:'office',title:'Dia de escritório',time:'08:00',endTime:'18:30',color:'blue',icon:'work',details:'Deslocamento + trabalho presencial.'},
  {id:'gym',title:'Academia',time:'12:00',endTime:'13:00',color:'green',icon:'gym',details:''},
  {id:'dogs',title:'Passear com os cachorros',time:'18:30',endTime:'19:00',color:'green',icon:'dogs',details:''},
  {id:'study',title:'Estudar 1h',time:'20:00',endTime:'21:00',color:'purple',icon:'study',details:''},
  {id:'clean',title:'Limpeza da casa',time:'19:00',endTime:'20:00',color:'yellow',icon:'trash',details:''},
  {id:'meal',title:'Preparar marmitas',time:'15:00',endTime:'17:00',color:'orange',icon:'food',details:''}
 ]}
}
function normalize(raw){const s=seed();return {...s,...raw,version:3,routines:(raw?.routines||s.routines).map(r=>({...classify(r.title),details:'',...r})),tasks:(raw?.tasks||s.tasks).map(t=>({...classify(t.title),endTime:'',details:'',...t})),priorities:raw?.priorities||{},completions:raw?.completions||{},notes:raw?.notes||s.notes,noteCategories:raw?.noteCategories||s.noteCategories,quickTemplates:raw?.quickTemplates||s.quickTemplates}}
function getWeek(base){const day=base.getDay(),m=new Date(base);m.setDate(base.getDate()+(day===0?-6:1-day));return Array.from({length:7},(_,i)=>addDays(m,i))}
function getMonthCells(base){const first=new Date(base.getFullYear(),base.getMonth(),1),offset=first.getDay()===0?-6:1-first.getDay(),start=addDays(first,offset);return Array.from({length:42},(_,i)=>addDays(start,i))}
function Icon({name,size=17}){const C=ICONS[name]||ICONS.default;return <C size={size}/>}

export default function App(){
 const [data,setData]=useState(null),[tab,setTab]=useState('today'),[date,setDate]=useState(new Date()),[weekAnchor,setWeekAnchor]=useState(new Date()),[monthAnchor,setMonthAnchor]=useState(new Date()),[taskEditor,setTaskEditor]=useState(null),[routineEditor,setRoutineEditor]=useState(null),[noteEditor,setNoteEditor]=useState(null),[showArchived,setShowArchived]=useState(false),[dragged,setDragged]=useState(null)
 useEffect(()=>{loadState(seed()).then(v=>setData(normalize(v)))},[])
 useEffect(()=>{if(data)saveState(data)},[data])
 if(!data)return <div className="loading-screen">Carregando sua rotina…</div>
 const save=fn=>setData(p=>typeof fn==='function'?fn(p):fn)
 const dateKey=keyOf(date),routinesToday=data.routines.filter(r=>r.days.includes(date.getDay())),tasksToday=data.tasks.filter(t=>t.date===dateKey),priorities=(data.priorities[dateKey]||[]).map((p,i)=>typeof p==='string'?{id:'legacy-'+i,title:p,color:'red'}:p)
 const week=getWeek(weekAnchor),monthCells=getMonthCells(monthAnchor)
 const done=(itemId,type='task',key=dateKey)=>!!data.completions[`${key}:${type}:${itemId}`]
 const toggle=(itemId,type='task',key=dateKey)=>save(p=>({...p,completions:{...p.completions,[`${key}:${type}:${itemId}`]:!p.completions[`${key}:${type}:${itemId}`]}}))
 const upsertTask=t=>save(p=>({...p,tasks:p.tasks.some(x=>x.id===t.id)?p.tasks.map(x=>x.id===t.id?t:x):[...p.tasks,{...t,id:id()}]}))
 const upsertRoutine=r=>save(p=>({...p,routines:p.routines.some(x=>x.id===r.id)?p.routines.map(x=>x.id===r.id?r:x):[...p.routines,{...r,id:id()}]}))
 const deleteTask=x=>confirm('Remover esta tarefa?')&&save(p=>({...p,tasks:p.tasks.filter(t=>t.id!==x)}))
 const deleteRoutine=x=>confirm('Remover esta rotina?')&&save(p=>({...p,routines:p.routines.filter(r=>r.id!==x)}))
 const moveTask=(taskId,newDate)=>save(p=>({...p,tasks:p.tasks.map(t=>t.id===taskId?{...t,date:newDate}:t)}))
 const dropOnDate=target=>{if(!dragged)return;if(dragged.kind==='task')moveTask(dragged.item.id,target);if(dragged.kind==='template')upsertTask({...dragged.item,id:null,date:target});setDragged(null)}
 const addPrioritySuggestion=title=>{const next=[...priorities,{id:id(),title,color:classify(title).color}];save(p=>({...p,priorities:{...p.priorities,[dateKey]:next}}))}
 const copyPreviousMonth=()=>{const cur=new Date(monthAnchor.getFullYear(),monthAnchor.getMonth(),1),prev=new Date(cur.getFullYear(),cur.getMonth()-1,1),pk=monthKey(prev),ck=monthKey(cur),source=data.tasks.filter(t=>t.date.startsWith(pk));if(!source.length)return alert('O mês anterior não tem tarefas pontuais para copiar.');const max=new Date(cur.getFullYear(),cur.getMonth()+1,0).getDate();save(p=>({...p,tasks:[...p.tasks,...source.map(t=>({...t,id:id(),date:`${ck}-${String(Math.min(Number(t.date.slice(-2)),max)).padStart(2,'0')}`}))]}))}
 const upsertNote=n=>save(p=>({...p,notes:p.notes.some(x=>x.id===n.id)?p.notes.map(x=>x.id===n.id?n:x):[...p.notes,{...n,id:id(),createdAt:Date.now()}],noteCategories:n.category&&!p.noteCategories.includes(n.category)?[...p.noteCategories,n.category]:p.noteCategories}))
 const deleteNote=x=>confirm('Excluir esta anotação?')&&save(p=>({...p,notes:p.notes.filter(n=>n.id!==x)}))
 const notes=data.notes.filter(n=>n.archived===showArchived).sort((a,b)=>Number(b.favorite)-Number(a.favorite)||b.createdAt-a.createdAt)
 return <div className="app-shell">
  <aside className="sidebar"><div className="brand"><div className="brand-mark">MR</div><div><strong>Minha Rotina</strong><span>um dia de cada vez</span></div></div><nav>
   <Nav active={tab==='today'} onClick={()=>setTab('today')} icon={<Home size={18}/>} label="Hoje"/><Nav active={tab==='week'} onClick={()=>setTab('week')} icon={<CalendarDays size={18}/>} label="Semana"/><Nav active={tab==='month'} onClick={()=>setTab('month')} icon={<CalendarDays size={18}/>} label="Mês"/><Nav active={tab==='routines'} onClick={()=>setTab('routines')} icon={<Repeat2 size={18}/>} label="Rotinas"/><Nav active={tab==='notes'} onClick={()=>setTab('notes')} icon={<StickyNote size={18}/>} label="Anotações"/>
  </nav><div className="legend">{COLORS.map(c=><span key={c.key}><i style={{background:c.hex}}/>{c.label}</span>)}</div><div className="sidebar-footer">Banco local: IndexedDB</div></aside>
  <main className="content">
   {tab!=='notes'&&<QuickBar templates={data.quickTemplates} onDrag={t=>setDragged({kind:'template',item:t})} onClick={t=>setTaskEditor({...t,id:null,date:dateKey})}/>}
   {tab==='today'&&<Today date={date} setDate={setDate} routines={routinesToday} tasks={tasksToday} priorities={priorities} done={done} toggle={toggle} setTaskEditor={setTaskEditor} setRoutineEditor={setRoutineEditor} deleteTask={deleteTask} deleteRoutine={deleteRoutine} save={save} addPrioritySuggestion={addPrioritySuggestion} />}
   {tab==='week'&&<Week week={week} setWeekAnchor={setWeekAnchor} data={data} dragged={dragged} setDragged={setDragged} dropOnDate={dropOnDate} setTaskEditor={setTaskEditor} deleteTask={deleteTask}/>} 
   {tab==='month'&&<Month monthAnchor={monthAnchor} setMonthAnchor={setMonthAnchor} cells={monthCells} data={data} dragged={dragged} setDragged={setDragged} dropOnDate={dropOnDate} setTaskEditor={setTaskEditor} copyPreviousMonth={copyPreviousMonth}/>} 
   {tab==='routines'&&<Routines data={data} setRoutineEditor={setRoutineEditor} deleteRoutine={deleteRoutine}/>} 
   {tab==='notes'&&<Notes notes={notes} showArchived={showArchived} setShowArchived={setShowArchived} setNoteEditor={setNoteEditor} save={save} deleteNote={deleteNote}/>} 
  </main>
  {taskEditor&&<TaskModal item={taskEditor} close={()=>setTaskEditor(null)} saveItem={x=>{upsertTask(x);setTaskEditor(null)}}/>}
  {routineEditor&&<RoutineModal item={routineEditor} close={()=>setRoutineEditor(null)} saveItem={x=>{upsertRoutine(x);setRoutineEditor(null)}}/>}
  {noteEditor&&<NoteModal item={noteEditor} categories={data.noteCategories} close={()=>setNoteEditor(null)} saveItem={x=>{upsertNote(x);setNoteEditor(null)}}/>}
 </div>
}

function Nav({active,onClick,icon,label}){return <button className={active?'active':''} onClick={onClick}>{icon}{label}</button>}
function Header({eyebrow,title,subtitle,actions}){return <header className="page-header"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{subtitle}</p></div><div className="date-actions">{actions}</div></header>}
function Card({title,eyebrow,action,children}){return <article className="card"><div className="card-heading"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2></div>{action}</div>{children}</article>}
function QuickBar({templates,onDrag,onClick}){return <div className="quick-bar"><div><Sparkles size={16}/><strong>Rápidos</strong></div>{templates.map(t=><button draggable onDragStart={()=>onDrag(t)} onClick={()=>onClick(t)} key={t.id} style={{'--item-color':colorHex(t.color)}}><GripVertical size={14}/><Icon name={t.icon}/>{t.title}</button>)}<small>arraste para um dia ou clique para editar antes</small></div>}

function Today({date,setDate,routines,tasks,priorities,done,toggle,setTaskEditor,setRoutineEditor,deleteTask,deleteRoutine,save,addPrioritySuggestion}){
 const dateKey=keyOf(date),suggestions=['Terminar a tarefa mais importante do trabalho','Estudar 1h','Ir à academia','Passear com os cachorros','Lavar roupa','Preparar marmitas','Resolver uma pendência da casa','Avançar no projeto pessoal','Planejar amanhã']
 const events=[...routines.map(r=>({...r,kind:'routine'})),...tasks.map(t=>({...t,kind:'task'}))]
 return <><Header eyebrow="Seu dia" title="Hoje" subtitle={ptDate.format(date)} actions={<><button className="icon-button" onClick={()=>setDate(addDays(date,-1))}><ChevronLeft size={18}/></button><button className="ghost-button" onClick={()=>setDate(new Date())}>Hoje</button><button className="icon-button" onClick={()=>setDate(addDays(date,1))}><ChevronRight size={18}/></button></>}/><section className="grid-main"><div className="stack"><Card title="Prioridades" eyebrow="Foco" action={<button className="small-button" onClick={()=>addPrioritySuggestion('Nova prioridade')}><CirclePlus size={15}/>Adicionar</button>}><div className="priority-suggestions"><span><Lightbulb size={14}/> Ideias:</span>{suggestions.map(s=><button key={s} onClick={()=>addPrioritySuggestion(s)}>{s}</button>)}</div>{!priorities.length&&<div className="empty-state">Escolha uma ideia acima ou adicione algo seu.</div>}{priorities.map((p,i)=><div className="priority-item" key={p.id}><span className="priority-number" style={{background:colorHex(p.color)}}>{i+1}</span><input value={p.title} onChange={e=>save(d=>({...d,priorities:{...d.priorities,[dateKey]:priorities.map(x=>x.id===p.id?{...x,title:e.target.value}:x)}}))}/><button className="mini-action" onClick={()=>save(d=>({...d,priorities:{...d.priorities,[dateKey]:priorities.filter(x=>x.id!==p.id)}}))}><Trash2 size={14}/></button></div>)}</Card><Card title="Dia completo — 24h" eyebrow="Linha do tempo"><DayTimeline events={events}/></Card></div><div className="stack"><Card title="Itens de hoje" eyebrow="Agenda" action={<button className="small-button" onClick={()=>setTaskEditor({id:null,title:'',date:dateKey,time:'',endTime:'',details:'',...classify('')})}><CirclePlus size={15}/>Tarefa</button>}>{events.sort((a,b)=>toMin(a.time)-toMin(b.time)).map(e=><div className={'agenda-row '+(done(e.id,e.kind==='routine'?'routine':'task')?'done':'')} style={{'--item-color':colorHex(e.color)}} key={e.kind+e.id}><button className="check-circle" onClick={()=>toggle(e.id,e.kind==='routine'?'routine':'task')}>{done(e.id,e.kind==='routine'?'routine':'task')&&<Check size={14}/>}</button><span className="color-stripe"/><span className="timeline-time">{e.time}{e.endTime?'–'+e.endTime:''}</span><span className="timeline-icon"><Icon name={e.icon}/></span><div className="timeline-copy"><strong>{e.title}</strong>{e.details&&<small>{e.details}</small>}</div><button className="mini-action" onClick={()=>e.kind==='routine'?setRoutineEditor(e):setTaskEditor(e)}><Pencil size={14}/></button><button className="mini-action danger" onClick={()=>e.kind==='routine'?deleteRoutine(e.id):deleteTask(e.id)}><Trash2 size={14}/></button></div>)}</Card><article className="card end-card"><MoonStar size={24}/><div><span className="eyebrow">À noite</span><h2>Planejar amanhã</h2><p>Revise prioridades e deixe o próximo dia pronto antes de dormir.</p></div></article></div></section></>
}
function DayTimeline({events}){return <div className="day24">{Array.from({length:24},(_,h)=><div className="hour-row" key={h}><span>{String(h).padStart(2,'0')}:00</span><div/></div>)}{events.map(e=>{if(!e.time)return null;let start=toMin(e.time),end=e.endTime?toMin(e.endTime):start+45;if(e.icon==='sleep'&&end<=start)end+=1440;const pieces=end>1440?[{s:start,e:1440},{s:0,e:end-1440}]:[{s:start,e:end}];return pieces.map((p,i)=><div className="timeline-block" key={e.id+'-'+i} title={e.details||e.title} style={{top:`${(p.s/1440)*100}%`,height:`${Math.max(((p.e-p.s)/1440)*100,1.8)}%`,background:colorHex(e.color)}}><Icon name={e.icon} size={13}/><span>{e.title}</span></div>)})}</div>}

function Week({week,setWeekAnchor,data,dragged,setDragged,dropOnDate,setTaskEditor,deleteTask}){return <><Header eyebrow="Visão geral" title="Semana" subtitle="Arraste tarefas ou itens rápidos entre os dias." actions={<><button className="icon-button" onClick={()=>setWeekAnchor(d=>addDays(d,-7))}><ChevronLeft size={18}/></button><button className="ghost-button" onClick={()=>setWeekAnchor(new Date())}>Esta semana</button><button className="icon-button" onClick={()=>setWeekAnchor(d=>addDays(d,7))}><ChevronRight size={18}/></button></>}/><section className="week-grid">{week.map(d=>{const k=keyOf(d),ts=data.tasks.filter(t=>t.date===k),rs=data.routines.filter(r=>r.days.includes(d.getDay()));return <article className="day-card drop-zone" onDragOver={e=>e.preventDefault()} onDrop={()=>dropOnDate(k)} key={k}><div className="day-card-header"><span>{WEEK.find(w=>w.key===d.getDay())?.short}</span><strong>{d.getDate()}</strong></div><div className="day-items">{rs.map(r=><div className="mini-item" style={{'--item-color':colorHex(r.color)}} key={r.id}><Icon name={r.icon} size={12}/>{r.time} {r.title}</div>)}{ts.map(t=><div draggable onDragStart={()=>setDragged({kind:'task',item:t})} className="mini-item task" style={{'--item-color':colorHex(t.color)}} key={t.id}><GripVertical size={12}/><Icon name={t.icon} size={12}/><span onClick={()=>setTaskEditor(t)}>{t.time} {t.title}</span><button onClick={()=>deleteTask(t.id)}><Trash2 size={11}/></button></div>)}</div><button className="add-day-task" onClick={()=>setTaskEditor({id:null,title:'',date:k,time:'',endTime:'',details:'',...classify('')})}><CirclePlus size={15}/> tarefa</button></article>})}</section></>}
function Month({monthAnchor,setMonthAnchor,cells,data,setDragged,dropOnDate,setTaskEditor,copyPreviousMonth}){return <><Header eyebrow="Planejamento" title={cap(ptMonth.format(monthAnchor))} subtitle="Arraste itens para reorganizar o mês." actions={<><button className="ghost-button" onClick={copyPreviousMonth}><Copy size={16}/>Copiar mês anterior</button><button className="icon-button" onClick={()=>setMonthAnchor(d=>new Date(d.getFullYear(),d.getMonth()-1,1))}><ChevronLeft size={18}/></button><button className="ghost-button" onClick={()=>setMonthAnchor(new Date())}>Este mês</button><button className="icon-button" onClick={()=>setMonthAnchor(d=>new Date(d.getFullYear(),d.getMonth()+1,1))}><ChevronRight size={18}/></button></>}/><div className="month-weekdays">{WEEK.map(w=><span key={w.key}>{w.short}</span>)}</div><section className="month-grid">{cells.map(d=>{const k=keyOf(d),ts=data.tasks.filter(t=>t.date===k),rs=data.routines.filter(r=>r.days.includes(d.getDay()));return <article className={'month-cell '+(d.getMonth()!==monthAnchor.getMonth()?'muted':'')} onDragOver={e=>e.preventDefault()} onDrop={()=>dropOnDate(k)} key={k}><div className="month-cell-head"><strong>{d.getDate()}</strong><button onClick={()=>setTaskEditor({id:null,title:'',date:k,time:'',endTime:'',details:'',...classify('')})}><CirclePlus size={13}/></button></div>{rs.slice(0,3).map(r=><div className="month-chip routine" style={{'--item-color':colorHex(r.color)}} key={r.id}><Icon name={r.icon} size={10}/>{r.title}</div>)}{ts.map(t=><div draggable onDragStart={()=>setDragged({kind:'task',item:t})} onClick={()=>setTaskEditor(t)} className="month-chip" style={{'--item-color':colorHex(t.color)}} key={t.id}><GripVertical size={10}/><Icon name={t.icon} size={10}/>{t.title}</div>)}</article>})}</section></>}

function Routines({data,setRoutineEditor,deleteRoutine}){return <><Header eyebrow="Automático" title="Rotinas" subtitle="A classificação tenta sugerir cor e ícone automaticamente pelo nome." actions={<button className="primary-button" onClick={()=>setRoutineEditor({id:null,title:'',time:'08:00',endTime:'',days:[1,2,3,4,5],details:'',...classify('')})}><CirclePlus size={16}/>Nova rotina</button>}/><section className="routine-list">{data.routines.map(r=><article className="routine-card" style={{'--item-color':colorHex(r.color)}} key={r.id}><div className="routine-icon"><Icon name={r.icon} size={20}/></div><div className="routine-main"><strong>{r.title}</strong><span>{r.time}{r.endTime?' – '+r.endTime:''}</span>{r.details&&<small>{r.details}</small>}<div className="weekday-pills">{WEEK.map(w=><span className={r.days.includes(w.key)?'on':''} key={w.key}>{w.short[0]}</span>)}</div></div><button className="mini-action" onClick={()=>setRoutineEditor(r)}><Pencil size={16}/></button><button className="mini-action danger" onClick={()=>deleteRoutine(r.id)}><Trash2 size={16}/></button></article>)}</section></>}

function Notes({notes,showArchived,setShowArchived,setNoteEditor,save,deleteNote}){return <><Header eyebrow="Quadro" title="Anotações" subtitle="Ideias, lembretes e informações que você quer guardar." actions={<><button className="ghost-button" onClick={()=>setShowArchived(v=>!v)}>{showArchived?<ArchiveRestore size={16}/>:<Archive size={16}/>} {showArchived?'Ver ativas':'Ver arquivadas'}</button><button className="primary-button" onClick={()=>setNoteEditor({id:null,title:'',body:'',category:'Ideias',color:'orange',favorite:false,archived:false,private:false})}><CirclePlus size={16}/>Nova anotação</button></>}/><div className="note-warning">Ocultar detalhes só esconde visualmente. Não use este quadro como gerenciador de senhas ou cofre de credenciais.</div><section className="notes-grid">{notes.map(n=><NoteCard key={n.id} note={n} edit={()=>setNoteEditor(n)} deleteNote={()=>deleteNote(n.id)} save={save}/>)}</section></>}
function NoteCard({note,edit,deleteNote,save}){const [revealed,setRevealed]=useState(!note.private);return <article className="note-card" style={{'--item-color':colorHex(note.color)}}><div className="note-top"><span className="note-category">{note.category}</span><div><button onClick={()=>save(d=>({...d,notes:d.notes.map(n=>n.id===note.id?{...n,favorite:!n.favorite}:n)}))}>{note.favorite?<PinOff size={14}/>:<Pin size={14}/>}</button><button onClick={edit}><Pencil size={14}/></button><button onClick={()=>save(d=>({...d,notes:d.notes.map(n=>n.id===note.id?{...n,archived:!n.archived}:n)}))}>{note.archived?<ArchiveRestore size={14}/>:<Archive size={14}/>}</button><button onClick={deleteNote}><Trash2 size={14}/></button></div></div><h3>{note.title}</h3>{note.private&&!revealed?<button className="reveal-note" onClick={()=>setRevealed(true)}><Eye size={15}/>Mostrar detalhes</button>:<><pre>{note.body}</pre>{note.private&&<button className="reveal-note" onClick={()=>setRevealed(false)}><EyeOff size={15}/>Ocultar detalhes</button>}</>}</article>}

function Modal({title,onClose,children}){return <div className="modal-backdrop"><section className="modal"><div className="modal-top"><h2>{title}</h2><button className="icon-button" onClick={onClose}><X size={18}/></button></div>{children}</section></div>}
function Field({label,children,hint}){return <label className="field"><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>}
function ColorPicker({value,onChange}){return <div className="color-picker">{COLORS.map(c=><button type="button" title={c.label} className={value===c.key?'selected':''} style={{background:c.hex}} onClick={()=>onChange(c.key)} key={c.key}/>)}</div>}
function IconPicker({value,onChange}){return <div className="icon-picker">{Object.keys(ICONS).filter(k=>k!=='default').map(k=><button type="button" className={value===k?'selected':''} onClick={()=>onChange(k)} key={k}><Icon name={k}/></button>)}</div>}
function TaskModal({item,close,saveItem}){const auto=classify(item.title||''),[x,setX]=useState({...auto,color:item.color||auto.color,icon:item.icon||auto.icon,endTime:'',details:'',...item});const changeTitle=title=>{const suggestion=classify(title);setX(p=>({...p,title,color:p.title? p.color:suggestion.color,icon:p.title? p.icon:suggestion.icon}))};return <Modal title={x.id?'Editar tarefa':'Nova tarefa'} onClose={close}><form onSubmit={e=>{e.preventDefault();if(x.title.trim())saveItem({...x,title:x.title.trim()})}}><Field label="Título" hint="A cor e o ícone são sugeridos automaticamente enquanto você começa a digitar."><input autoFocus value={x.title} onChange={e=>changeTitle(e.target.value)}/></Field><div className="field-row"><Field label="Dia"><input type="date" value={x.date} onChange={e=>setX({...x,date:e.target.value})}/></Field><Field label="Início"><input type="time" value={x.time} onChange={e=>setX({...x,time:e.target.value})}/></Field><Field label="Fim"><input type="time" value={x.endTime||''} onChange={e=>setX({...x,endTime:e.target.value})}/></Field></div><Field label="Detalhes"><textarea rows="4" value={x.details||''} onChange={e=>setX({...x,details:e.target.value})} placeholder="Notas, contexto, checklist, endereço..."/></Field><Field label="Cor"><ColorPicker value={x.color} onChange={color=>setX({...x,color})}/></Field><Field label="Ícone"><IconPicker value={x.icon} onChange={icon=>setX({...x,icon})}/></Field><Actions close={close}/></form></Modal>}
function RoutineModal({item,close,saveItem}){const auto=classify(item.title||''),[x,setX]=useState({...auto,color:item.color||auto.color,icon:item.icon||auto.icon,days:[],details:'',...item});const changeTitle=title=>{const suggestion=classify(title);setX(p=>({...p,title,color:p.title?p.color:suggestion.color,icon:p.title?p.icon:suggestion.icon}))};return <Modal title={x.id?'Editar rotina':'Nova rotina'} onClose={close}><form onSubmit={e=>{e.preventDefault();if(x.title.trim()&&x.days.length)saveItem({...x,title:x.title.trim()})}}><Field label="Título"><input value={x.title} onChange={e=>changeTitle(e.target.value)}/></Field><div className="field-row"><Field label="Entrada / início"><input type="time" value={x.time} onChange={e=>setX({...x,time:e.target.value})}/></Field><Field label="Saída / fim"><input type="time" value={x.endTime||''} onChange={e=>setX({...x,endTime:e.target.value})}/></Field></div><Field label="Dias"><div className="day-selector">{WEEK.map(w=><button type="button" className={x.days.includes(w.key)?'selected':''} onClick={()=>setX({...x,days:x.days.includes(w.key)?x.days.filter(d=>d!==w.key):[...x.days,w.key]})} key={w.key}>{w.short}</button>)}</div></Field><Field label="Detalhes"><textarea rows="3" value={x.details||''} onChange={e=>setX({...x,details:e.target.value})}/></Field><Field label="Cor"><ColorPicker value={x.color} onChange={color=>setX({...x,color})}/></Field><Field label="Ícone"><IconPicker value={x.icon} onChange={icon=>setX({...x,icon})}/></Field><Actions close={close}/></form></Modal>}
function NoteModal({item,categories,close,saveItem}){const [x,setX]=useState(item);return <Modal title={x.id?'Editar anotação':'Nova anotação'} onClose={close}><form onSubmit={e=>{e.preventDefault();if(x.title.trim())saveItem({...x,title:x.title.trim()})}}><Field label="Título"><input autoFocus value={x.title} onChange={e=>setX({...x,title:e.target.value})}/></Field><Field label="Categoria"><input list="note-categories" value={x.category} onChange={e=>setX({...x,category:e.target.value})}/><datalist id="note-categories">{categories.map(c=><option key={c} value={c}/>)}</datalist></Field><Field label="Anotação"><textarea rows="9" value={x.body} onChange={e=>setX({...x,body:e.target.value})}/></Field><Field label="Cor"><ColorPicker value={x.color} onChange={color=>setX({...x,color})}/></Field><div className="toggle-row"><label><input type="checkbox" checked={x.favorite} onChange={e=>setX({...x,favorite:e.target.checked})}/> Favorito</label><label><input type="checkbox" checked={x.private} onChange={e=>setX({...x,private:e.target.checked})}/> Ocultar detalhes por padrão</label></div><Actions close={close}/></form></Modal>}
function Actions({close}){return <div className="modal-actions"><button type="button" className="ghost-button" onClick={close}>Cancelar</button><button className="primary-button">Salvar</button></div>}
