import { useMemo, useState } from 'react'
import { CalendarDays, Check, ChevronLeft, ChevronRight, CirclePlus, ClipboardCheck, Clock3, Dumbbell, Home, MoonStar, PawPrint, Repeat2, Trash2, X } from 'lucide-react'

const STORAGE_KEY='minha-rotina-v1'
const weekdays=[{key:1,short:'Seg'},{key:2,short:'Ter'},{key:3,short:'Qua'},{key:4,short:'Qui'},{key:5,short:'Sex'},{key:6,short:'Sáb'},{key:0,short:'Dom'}]
const seed={routines:[
{id:'work',title:'Trabalho',time:'09:00',endTime:'18:00',days:[1,2,3,4,5],icon:'work'},
{id:'gym',title:'Academia',time:'12:00',endTime:'',days:[1,2,3,4,5],icon:'gym'},
{id:'dogs',title:'Passear com os cachorros',time:'18:30',endTime:'',days:[1,2,3,4,5,6,0],icon:'dogs'},
{id:'study',title:'Estudar 1h',time:'20:00',endTime:'21:00',days:[1,2,3,4,5,6,0],icon:'study'},
{id:'trash',title:'Colocar lixo para fora',time:'08:15',endTime:'',days:[1,3,5],icon:'trash'},
{id:'recycle',title:'Reciclável',time:'09:00',endTime:'',days:[6],icon:'trash'}],tasks:[],priorities:{},completions:{}}
const loadData=()=>{try{const s=localStorage.getItem(STORAGE_KEY);return s?JSON.parse(s):seed}catch{return seed}}
const keyOf=d=>[d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')
const ptDate=new Intl.DateTimeFormat('pt-BR',{weekday:'long',day:'2-digit',month:'long'})
const getWeek=base=>{const day=base.getDay(),m=new Date(base);m.setDate(base.getDate()+(day===0?-6:1-day));return Array.from({length:7},(_,i)=>{const d=new Date(m);d.setDate(m.getDate()+i);return d})}
function I({type,size=18}){if(type==='gym')return <Dumbbell size={size}/>;if(type==='dogs')return <PawPrint size={size}/>;if(type==='study')return <ClipboardCheck size={size}/>;if(type==='trash')return <Trash2 size={size}/>;return <Clock3 size={size}/>}
function Modal({title,onClose,children}){return <div className="modal-backdrop"><section className="modal"><div className="modal-top"><h2>{title}</h2><button className="icon-button" onClick={onClose}><X size={18}/></button></div>{children}</section></div>}
function Empty({children}){return <div className="empty-state">{children}</div>}

export default function App(){
 const [data,setData]=useState(loadData),[tab,setTab]=useState('today'),[date,setDate]=useState(new Date()),[weekAnchor,setWeekAnchor]=useState(new Date()),[taskModal,setTaskModal]=useState(false),[routineModal,setRoutineModal]=useState(false),[closeModal,setCloseModal]=useState(false)
 const save=n=>{setData(n);localStorage.setItem(STORAGE_KEY,JSON.stringify(n))},dateKey=keyOf(date),day=date.getDay()
 const routines=useMemo(()=>data.routines.filter(r=>r.days.includes(day)).sort((a,b)=>a.time.localeCompare(b.time)),[data.routines,day]),tasks=useMemo(()=>data.tasks.filter(t=>t.date===dateKey),[data.tasks,dateKey]),priorities=data.priorities[dateKey]||['','',''],week=getWeek(weekAnchor)
 const done=(id,type='task',k=dateKey)=>!!data.completions[k+':'+type+':'+id]
 const toggle=(id,type='task')=>{const k=dateKey+':'+type+':'+id;save({...data,completions:{...data.completions,[k]:!data.completions[k]}})}
 const move=n=>{const d=new Date(date);d.setDate(d.getDate()+n);setDate(d)}
 return <div className="app-shell">
  <aside className="sidebar"><div className="brand"><div className="brand-mark">MR</div><div><strong>Minha Rotina</strong><span>um dia de cada vez</span></div></div><nav><button className={tab==='today'?'active':''} onClick={()=>setTab('today')}><Home size={18}/>Hoje</button><button className={tab==='week'?'active':''} onClick={()=>setTab('week')}><CalendarDays size={18}/>Semana</button><button className={tab==='routines'?'active':''} onClick={()=>setTab('routines')}><Repeat2 size={18}/>Rotinas</button></nav><div className="sidebar-footer">Dados salvos neste navegador</div></aside>
  <main className="content">
   {tab==='today'&&<><Header eyebrow="Seu dia" title="Hoje" subtitle={ptDate.format(date)} actions={<><button className="icon-button" onClick={()=>move(-1)}><ChevronLeft size={18}/></button><button className="ghost-button" onClick={()=>setDate(new Date())}>Hoje</button><button className="icon-button" onClick={()=>move(1)}><ChevronRight size={18}/></button></>}/><section className="grid-main"><div className="stack"><article className="card priority-card"><div className="card-heading"><div><span className="eyebrow">Foco</span><h2>3 prioridades</h2></div><small>defina na noite anterior</small></div><div className="priority-list">{[0,1,2].map(i=><label className="priority-row" key={i}><span>{i+1}</span><input value={priorities[i]||''} onChange={e=>{const p=[...priorities];p[i]=e.target.value;save({...data,priorities:{...data.priorities,[dateKey]:p}})}} placeholder={i?'Adicionar prioridade':'O que mais importa hoje?'}/></label>)}</div></article><article className="card"><div className="card-heading"><div><span className="eyebrow">Agenda base</span><h2>Rotina de hoje</h2></div></div><div className="timeline">{!routines.length&&<Empty>Nenhuma rotina para este dia.</Empty>}{routines.map(r=>{const d=done(r.id,'routine');return <button key={r.id} className={'timeline-item '+(d?'done':'')} onClick={()=>toggle(r.id,'routine')}><span className="timeline-time">{r.time}</span><span className="timeline-icon"><I type={r.icon}/></span><span className="timeline-copy"><strong>{r.title}</strong>{r.endTime&&<small>até {r.endTime}</small>}</span><span className="check-circle">{d&&<Check size={14}/>}</span></button>})}</div></article></div><div className="stack"><article className="card"><div className="card-heading"><div><span className="eyebrow">Pontual</span><h2>Tarefas</h2></div><button className="small-button" onClick={()=>setTaskModal(true)}><CirclePlus size={16}/>Adicionar</button></div>{!tasks.length&&<Empty>Nada extra para hoje. Ótimo sinal.</Empty>}{tasks.map(t=>{const d=done(t.id);return <div className={'task-row '+(d?'done':'')} key={t.id}><button className="check-circle large" onClick={()=>toggle(t.id)}>{d&&<Check size={14}/>}</button><span>{t.title}</span><button className="task-delete" onClick={()=>save({...data,tasks:data.tasks.filter(x=>x.id!==t.id)})}><Trash2 size={15}/></button></div>})}</article><article className="card end-card"><MoonStar size={24}/><div><span className="eyebrow">À noite</span><h2>Encerrar o dia</h2><p>Veja o que ficou e deixe amanhã pronto.</p></div><button className="primary-button" onClick={()=>setCloseModal(true)}>Encerrar dia</button></article></div></section></>}
   {tab==='week'&&<><Header eyebrow="Visão geral" title="Semana" subtitle="Distribua o que importa sem lotar todos os dias." actions={<><button className="icon-button" onClick={()=>{const d=new Date(weekAnchor);d.setDate(d.getDate()-7);setWeekAnchor(d)}}><ChevronLeft size={18}/></button><button className="ghost-button" onClick={()=>setWeekAnchor(new Date())}>Esta semana</button><button className="icon-button" onClick={()=>{const d=new Date(weekAnchor);d.setDate(d.getDate()+7);setWeekAnchor(d)}}><ChevronRight size={18}/></button></>}/><section className="week-grid">{week.map(d=>{const k=keyOf(d),ts=data.tasks.filter(t=>t.date===k),rs=data.routines.filter(r=>r.days.includes(d.getDay()));return <article className={'day-card '+(k===keyOf(new Date())?'today':'')} key={k}><div className="day-card-header"><span>{weekdays.find(w=>w.key===d.getDay())?.short}</span><strong>{String(d.getDate()).padStart(2,'0')}</strong></div><div className="day-items">{rs.slice(0,4).map(r=><div className="mini-item" key={r.id}><span>{r.time}</span>{r.title}</div>)}{ts.map(t=><div className="mini-item task" key={t.id}>• {t.title}</div>)}</div><button className="add-day-task" onClick={()=>{setDate(d);setTaskModal(true)}}><CirclePlus size={15}/> tarefa</button></article>})}</section></>}
   {tab==='routines'&&<><Header eyebrow="Automático" title="Rotinas" subtitle="O que se repete não precisa ser decidido todo dia." actions={<button className="primary-button" onClick={()=>setRoutineModal(true)}><CirclePlus size={16}/> Nova rotina</button>}/><section className="routine-list">{data.routines.map(r=><article className="routine-card" key={r.id}><div className="routine-icon"><I type={r.icon}/></div><div className="routine-main"><strong>{r.title}</strong><span>{r.time}{r.endTime?' – '+r.endTime:''}</span><div className="weekday-pills">{weekdays.map(w=><span className={r.days.includes(w.key)?'on':''} key={w.key}>{w.short[0]}</span>)}</div></div><button className="task-delete" onClick={()=>save({...data,routines:data.routines.filter(x=>x.id!==r.id)})}><Trash2 size={16}/></button></article>)}</section></>}
  </main>
  {taskModal&&<TaskModal date={dateKey} close={()=>setTaskModal(false)} saveTask={(title,d)=>{save({...data,tasks:[...data.tasks,{id:crypto.randomUUID(),title,date:d}]});setTaskModal(false)}}/>}
  {routineModal&&<RoutineModal close={()=>setRoutineModal(false)} saveRoutine={r=>{save({...data,routines:[...data.routines,{...r,id:crypto.randomUUID()}]});setRoutineModal(false)}}/>}
  {closeModal&&<CloseModal date={date} tasks={tasks} routines={routines} done={done} close={()=>setCloseModal(false)} moveTask={(id,d)=>save({...data,tasks:data.tasks.map(t=>t.id===id?{...t,date:d}:t)})} finish={p=>{const d=new Date(date);d.setDate(d.getDate()+1);save({...data,priorities:{...data.priorities,[keyOf(d)]:p}});setCloseModal(false)}}/>}
 </div>
}
function Header({eyebrow,title,subtitle,actions}){return <header className="page-header"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{subtitle}</p></div><div className="date-actions">{actions}</div></header>}
function TaskModal({date,close,saveTask}){const [title,setTitle]=useState(''),[d,setD]=useState(date);return <Modal title="Nova tarefa" onClose={close}><form onSubmit={e=>{e.preventDefault();if(title.trim())saveTask(title.trim(),d)}}><Field label="Tarefa"><input autoFocus value={title} onChange={e=>setTitle(e.target.value)} placeholder="Ex.: lavar roupa"/></Field><Field label="Dia"><input type="date" value={d} onChange={e=>setD(e.target.value)}/></Field><Actions close={close} label="Adicionar"/></form></Modal>}
function RoutineModal({close,saveRoutine}){const [title,setTitle]=useState(''),[time,setTime]=useState('08:00'),[endTime,setEndTime]=useState(''),[days,setDays]=useState([1,2,3,4,5]),[icon,setIcon]=useState('work');return <Modal title="Nova rotina" onClose={close}><form onSubmit={e=>{e.preventDefault();if(title.trim()&&days.length)saveRoutine({title:title.trim(),time,endTime,days,icon})}}><Field label="Nome"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Ex.: preparar marmitas"/></Field><div className="field-row"><Field label="Início"><input type="time" value={time} onChange={e=>setTime(e.target.value)}/></Field><Field label="Fim"><input type="time" value={endTime} onChange={e=>setEndTime(e.target.value)}/></Field></div><Field label="Tipo"><select value={icon} onChange={e=>setIcon(e.target.value)}><option value="work">Geral / trabalho</option><option value="gym">Academia</option><option value="dogs">Cachorros</option><option value="study">Estudo</option><option value="trash">Casa / lixo</option></select></Field><Field label="Dias"><div className="day-selector">{weekdays.map(w=><button type="button" className={days.includes(w.key)?'selected':''} onClick={()=>setDays(p=>p.includes(w.key)?p.filter(x=>x!==w.key):[...p,w.key])} key={w.key}>{w.short}</button>)}</div></Field><Actions close={close} label="Salvar rotina"/></form></Modal>}
function Field({label,children}){return <label className="field"><span>{label}</span>{children}</label>}
function Actions({close,label}){return <div className="modal-actions"><button type="button" className="ghost-button" onClick={close}>Cancelar</button><button className="primary-button">{label}</button></div>}
function CloseModal({date,tasks,routines,done,close,moveTask,finish}){const tomorrow=new Date(date);tomorrow.setDate(tomorrow.getDate()+1);const tk=keyOf(tomorrow),unfinished=tasks.filter(t=>!done(t.id)),completed=[...tasks.map(t=>done(t.id)),...routines.map(r=>done(r.id,'routine'))].filter(Boolean).length,[next,setNext]=useState(['','','']);return <Modal title="Encerrar o dia" onClose={close}><div className="day-summary"><div><strong>{completed}</strong><span>itens concluídos</span></div><div><strong>{unfinished.length}</strong><span>tarefas pendentes</span></div></div>{unfinished.length>0&&<div className="close-section"><h3>Pendências</h3>{unfinished.map(t=><div className="pending-row" key={t.id}><span>{t.title}</span><button className="small-button" onClick={()=>moveTask(t.id,tk)}>Mover para amanhã</button></div>)}</div>}<div className="close-section"><h3>3 prioridades de amanhã</h3>{[0,1,2].map(i=><label className="priority-row compact" key={i}><span>{i+1}</span><input value={next[i]} onChange={e=>{const n=[...next];n[i]=e.target.value;setNext(n)}} placeholder={i?'Adicionar prioridade':'Principal foco de amanhã'}/></label>)}</div><div className="modal-actions"><button className="ghost-button" onClick={close}>Agora não</button><button className="primary-button" onClick={()=>finish(next)}>Finalizar dia</button></div></Modal>}
