import React,{useEffect,useMemo,useState}from'react'
import{Check,ChevronDown,ChevronUp,CirclePlus,Clock3,Inbox,Pencil,Trash2,X}from'lucide-react'
import{loadState,saveState}from'./storage'
import'./task-inbox.css'

const uid=()=>crypto.randomUUID(),today=()=>new Date().toISOString().slice(0,10)
const empty={title:'',details:'',priority:'normal',estimate:30}
const splitEstimate=minutes=>({hours:Math.floor((Number(minutes)||0)/60),minutes:(Number(minutes)||0)%60})
const totalEstimate=(hours,minutes)=>Math.max(5,(Number(hours)||0)*60+(Number(minutes)||0))
const formatEstimate=minutes=>{const total=Number(minutes)||0,h=Math.floor(total/60),m=total%60;if(h&&m)return`${h}h ${m}min`;if(h)return`${h}h`;return`${m||5} min`}

export default function TaskInbox(){
 const[items,setItems]=useState([]),[open,setOpen]=useState(false),[form,setForm]=useState(empty),[editing,setEditing]=useState(null),[filter,setFilter]=useState('pending')
 const estimateParts=splitEstimate(form.estimate)
 useEffect(()=>{loadState({taskInbox:[]}).then(s=>setItems(Array.isArray(s?.taskInbox)?s.taskInbox:[])).catch(()=>{})},[])
 const persist=async next=>{setItems(next);const state=await loadState({});await saveState({...state,taskInbox:next})}
 const visible=useMemo(()=>items.filter(x=>filter==='all'||(filter==='done'?x.done:!x.done)).sort((a,b)=>(a.done-b.done)||({high:0,normal:1,low:2}[a.priority]-{high:0,normal:1,low:2}[b.priority])||(b.createdAt-a.createdAt)),[items,filter])
 const submit=e=>{e.preventDefault();if(!form.title.trim())return;const next=editing?items.map(x=>x.id===editing?{...x,...form}:x):[...items,{...form,id:uid(),done:false,createdAt:Date.now()}];persist(next);setForm(empty);setEditing(null)}
 const edit=x=>{setForm({title:x.title,details:x.details||'',priority:x.priority||'normal',estimate:x.estimate||30});setEditing(x.id);setOpen(true)}
 const schedule=async x=>{const state=await loadState({});const task={id:uid(),title:x.title,details:x.details||'',date:today(),time:'',endTime:'',repeat:'none',until:today(),excludedDates:[],weekdays:[],color:x.priority==='high'?'red':'gray',icon:'default'};await saveState({...state,tasks:[...(state.tasks||[]),task],taskInbox:items});window.location.reload()}
 const setHours=v=>setForm({...form,estimate:totalEstimate(v,estimateParts.minutes)})
 const setMinutes=v=>setForm({...form,estimate:totalEstimate(estimateParts.hours,v)})
 return <div className="inbox-wrap"><button className="inbox-launch" onClick={()=>setOpen(v=>!v)}><Inbox size={18}/><span>Lista de tarefas</span><b>{items.filter(x=>!x.done).length}</b>{open?<ChevronDown size={15}/>:<ChevronUp size={15}/>}</button>{open&&<section className="inbox-panel"><header><div><small>PARA QUANDO DER</small><h2>Lista de tarefas</h2><p>Anote agora e encaixe no dia quando tiver tempo ou precisar.</p></div><button onClick={()=>setOpen(false)}><X size={18}/></button></header><form onSubmit={submit}><input autoFocus placeholder="Ex.: organizar documentos, comprar ração..." value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><textarea placeholder="Detalhes (opcional)" value={form.details} onChange={e=>setForm({...form,details:e.target.value})}/><div className="inbox-form-row"><select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}><option value="high">Importante</option><option value="normal">Normal</option><option value="low">Quando sobrar tempo</option></select><div className="inbox-duration"><Clock3 size={14}/><label><input type="number" min="0" max="23" value={estimateParts.hours} onChange={e=>setHours(e.target.value)}/><span>h</span></label><label><input type="number" min="0" max="55" step="5" value={estimateParts.minutes} onChange={e=>setMinutes(e.target.value)}/><span>min</span></label></div><button><CirclePlus size={15}/>{editing?'Salvar':'Adicionar'}</button></div></form><nav><button className={filter==='pending'?'active':''} onClick={()=>setFilter('pending')}>Pendentes</button><button className={filter==='done'?'active':''} onClick={()=>setFilter('done')}>Concluídas</button><button className={filter==='all'?'active':''} onClick={()=>setFilter('all')}>Todas</button></nav><div className="inbox-list">{visible.length===0&&<p className="inbox-empty">Nenhuma tarefa aqui.</p>}{visible.map(x=><article key={x.id} className={x.done?'done':''} data-priority={x.priority}><button className="inbox-check" onClick={()=>persist(items.map(i=>i.id===x.id?{...i,done:!i.done}:i))}>{x.done&&<Check size={14}/>}</button><div><strong>{x.title}</strong>{x.details&&<p>{x.details}</p>}<small><Clock3 size={12}/>{formatEstimate(x.estimate||30)} · {x.priority==='high'?'Importante':x.priority==='low'?'Quando sobrar tempo':'Normal'}</small></div>{!x.done&&<button className="inbox-use" onClick={()=>schedule(x)}>Colocar hoje</button>}<button onClick={()=>edit(x)}><Pencil size={14}/></button><button onClick={()=>confirm('Remover esta tarefa da lista?')&&persist(items.filter(i=>i.id!==x.id))}><Trash2 size={14}/></button></article>)}</div></section>}</div>
}
